### PR TITLE
Added Fedora Specific Instructions

### PR DESCRIPTION
**Pull request by lucabotti**
I added Fedora 33 requirement instructions. Feel free to add.

### CODE REVIEW

**Comment by rschroll** [comment]
Thanks for doing this!  I'm guessing this means it works on Fedora?

I think we should probably unprivilege Debian, creating generic instructions with Debian/Fedora/etc instructions below.  Feel free to take a stab at that if you like; if not I can do that from your instructions.

This actually raises a good point that I hadn't considered -- if you install pyfuse3 through your package manager, as opposed to through pip, it should come in compiled form already.  Thus, you probably don't need `fuse3-devel` to make the install work.  Would you be willing to test that out?  If you don't have the time, I can try it in a docker container at some point.

Interestingly, it appears that pyfuse3 isn't in apt, so score one for Fedora.

**Comment by lucabotti** [comment]
Yes it works properly on Fedora. I will test for removal of fuse3-devel



Il giorno mar 9 feb 2021 alle ore 02:28 Robert Schroll <
notifications@github.com> ha scritto:

**Comment by rschroll** [comment]
I'm going to wait until we see if #6 will be merged.  If so, I'll need to completely rewrite the installation directions.

**Comment by lucabotti** [comment]
If needed, I can give support on that

**Comment by rschroll** [comment]
Thanks.  We'll see what happens with #2.  If it works, I'll rewrite the instructions and ask you to proofread the Fedora version.

**Comment by GeeWee** [comment]
These instructions were a huge help to me, thanks!

**Comment by rschroll** [comment]
I'm getting ready for a new release, which has scrambled the install instructions a bit.  Here's what I currently have: https://github.com/rschroll/rmfuse/blob/release-0.2.0/README.md#fedora-based-systems

Could you take a look to see that I've accurately described what you have to do for Fedora?  If you can test it, it would be appreciated, since some of the install details have changed.  Note that you'll need to pass `--pre` to a pip install command, so that you get a new version of rmfuse that supports these options.

Thanks!

**Comment by lucabotti** [comment]
Hi,

had to add the following:


fuse3-libs python3-fusepy fuse3-libs fuse3-devel python3-devel

to make the pip install work

This on a freshly installed system.

Regards




Il giorno dom 28 feb 2021 alle ore 23:39 Robert Schroll <
notifications@github.com> ha scritto:

**Comment by rschroll** [comment]
Thanks.  I've updated the README appropriately.

**Pull request closed without merging**
